---
title: "02_agency_demo_improv_new"
output: html_document
date: "2023-03-06"
---

```{r setup, include=FALSE}
# ***FIRST***: load libraries from `00_load_dependencies.R`
# read dataset ----
r <- read.socrata("https://data.cityofnewyork.us/resource/423i-ukqr.json?$limit=9999999999", stringsAsFactors = F)
```

```{r}
# cleaning data -----------
r$number_of_employees_middle <- as.numeric(gsub("<5", "2.5", r$number_of_employees))
r$number_of_employees_top <- as.numeric(gsub("<5", "4", r$number_of_employees))
r$number_of_employees_bottom <- as.numeric(gsub("<5", "1", r$number_of_employees))
r$agency_name <- gsub("'", "", r$agency_name)
r$gender <- gsub("Unknown or Choose Not to Disclose", "Unknown", r$gender)
  
# shorten the names, to acroynms of agencies for diagnostic plots ----
r1 <- r %>%  mutate_at(vars(c(1:3,7:10)), as.factor)
  
r1$agency <- r1$agency_name
  
r1$agency_name <- recode(r1$agency, 
                         `ADMINISTRATION FOR CHILDRENS SERVICES` = "ACS",
                         `BUSINESS INTEGRITY COMMISSION` = "BIC", 
                         `DEPARTMENT FOR THE AGING` = "DFTA", 
                         `DEPARTMENT OF BUILDINGS` = "DOB", 
                         `DEPARTMENT OF CITY PLANNING` = "DCP", 
                         `DEPARTMENT OF CITYWIDE ADMINISTRATIVE SERVICES` = "DCAS",
                         `DEPARTMENT OF CONSUMER AFFAIRS` = "DCA", 
                         `DEPARTMENT OF CORRECTION` = "DOC", 
                         `DEPARTMENT OF CULTURAL AFFAIRS` = "DCLA", 
                         `DEPARTMENT OF DESIGN AND CONSTRUCTION` = "DDC", 
                         `DEPARTMENT OF EDUCATION (NON-PEDAGOGICAL)` = "DOE*", 
                         `DEPARTMENT OF ENVIRONMENTAL PROTECTION` = "DEP", 
                         `DEPARTMENT OF FINANCE` = "DOF", 
                         `DEPARTMENT OF HEALTH AND MENTAL HYGIENE` = "DOHMH", 
                         `DEPARTMENT OF HOMELESS SERVICES` = "DHS", 
                         `DEPARTMENT OF INFORMATION TECHNOLOGY AND TELECOMMUNICATIONS` = "DOITT",
                         `DEPARTMENT OF INVESTIGATION` = "DOI", 
                         `DEPARTMENT OF PARKS AND RECREATION` = "PARKS", 
                         `DEPARTMENT OF PROBATION` = "DOP", 
                         `DEPARTMENT OF RECORDS AND INFORMATION SERVICES` = "DORIS", 
                         `DEPARTMENT OF SANITATION` = "DSNY", 
                         `DEPARTMENT OF SMALL BUSINESS SERVICES` = "SBS", 
                         `DEPARTMENT OF TRANSPORTATION` = "DOT", 
                           `DEPARTMENT OF VETERANS SERVICES` = "DVS", 
                           `DEPARTMENT OF YOUTH AND COMMUNITY DEVELOPMENT` = "DYCD", 
                           `FIRE DEPARTMENT` = "FDNY", 
                           `HOUSING PRESERVATION AND DEVELOPMENT` = "HPD", 
                           `HUMAN RESOURCES ADMINISTRATION/DEPARTMENT OF SOCIAL SERVICES` = "HRA/DSS", 
                           `LAW DEPARTMENT` = "LAW", 
                           `MAYORS OFFICE OF CONTRACT SERVICES` = "MOCS", 
                           `OFFICE OF ADMINISTRATIVE TRIALS AND HEARINGS`= "OATH", 
                           `OFFICE OF EMERGENCY MANAGEMENT` = "OEM", 
                           `OFFICE OF LABOR RELATIONS` = "OLR", 
                           `OFFICE OF MANAGEMENT AND BUDGET` = "OMB", 
                           `OFFICE OF THE MAYOR` = "MAYORS", 
                           `POLICE DEPARTMENT` = "NYPD" )
```

```{r}
# get avg pay ----------
r1$lower_pay <- as.numeric(unlist(lapply(strsplit(r1$pay_band, "-"), "[", 1)))
r1$higher_pay <- as.numeric(unlist(lapply(strsplit(r1$pay_band, "-"), "[", 2)))
r1$avg_pay <- (r1$lower_pay + r1$higher_pay) /2
```

```{r}
# ***TO DO: UPDATE NAMING CONVENTIONS***
recode_re <- function(r1) {
  temp <- r1
  temp$race1 <- as.character(temp$race)
  u= c("Two or More Races",
       "American Indian or Alaska Native",
       "Unknown or Choose Not to Disclose")
  temp$race1[temp$race1 %in% u]  <- "Other"
  temp$race1[temp$race1 == "Native Hawaiian or Pacific Islander" | temp$race1 == "Asian"] <- "Asian"
  temp$race1[temp$race1 == "Black or African American"] <- "Black"
  
  temp$race_ethnicity <- temp$race1
  
  temp <- temp %>% mutate(race_ethnicity = recode(race1, "Black" = "NH Black", # BLACK ALONE
                                                     "White" = "NH White", # WHITE ALONE
                                                     "Other" = "NH SOR or Race UCND", # AMERICAN INDIAN ALONE, # NATIVE, NOT SPEC/NO OTHER, AK NATIVE ALONE, SOR, TWO OR MORE
                                                     "Asian" = "NH Asian")) # ASIAN ALONE | NATIVE HAWAIIAN OR PACIFIC ISL
  
  temp[temp$ethnicity=="Unknown or Choose Not to Disclose",]$race_ethnicity <-
  rep("Ethnicity Unknown or Choose Not to Disclose", length(temp[temp$ethnicity=="Unknown or Choose Not to Disclose",]$race_ethnicity))
  
  temp[temp$ethnicity=="Hispanic or Latino",]$race_ethnicity <-
  rep("Hispanic or Latino", length(temp[temp$ethnicity=="Hispanic or Latino",]$race_ethnicity))
  
  temp$race1[temp$race1 == "Unknown or Choose Not to Disclose"] <- "NH SOR or Race UCND"
  return(temp)
}
```

```{r}
r1 <- recode_re(r1)
```

```{r}
# filter to full-time ---------
r2 <- r1 %>% filter(employee_status=="Full-Time")
```

```{r}
r2$gender2 <- recode(r2$gender, 
                    "Non-binary" = "Other",
                    "Other Gender" = "Other",
                    "Unknown" = "Other") # because each of these groups are really small on their own..
```

```{r}
# eda demographic changes -----------

city_pop <- r2 %>% group_by(data_year) %>% 
  summarise(number_of_employees_bottom = sum(number_of_employees_bottom),
            number_of_employees_middle = sum(number_of_employees_middle),
            number_of_employees_top= sum(number_of_employees_top)) %>% 
  mutate(pct.chg_middle = formattable::percent((number_of_employees_middle - lag(number_of_employees_middle))/lag(number_of_employees_middle)),
         pct.chg_top = formattable::percent((number_of_employees_top- lag(number_of_employees_top))/lag(number_of_employees_top)),
         pct.chg_bottom = (formattable::percent(number_of_employees_bottom - lag(number_of_employees_bottom))/lag(number_of_employees_bottom)),
         diff_middle = number_of_employees_middle - lag(number_of_employees_middle),
         diff_top = number_of_employees_top - lag(number_of_employees_top),
         diff_bottom =  number_of_employees_bottom - lag(number_of_employees_bottom)) 

####
city_race <- r2 %>% group_by(data_year, race_ethnicity) %>% 
  summarise(number_of_employees_bottom = sum(number_of_employees_bottom),
            number_of_employees_middle = sum(number_of_employees_middle),
            number_of_employees_top= sum(number_of_employees_top)) %>% 
  group_by(race_ethnicity) %>%
  arrange(data_year, race_ethnicity) %>%
  mutate(pct.chg_middle = formattable::percent((number_of_employees_middle - lag(number_of_employees_middle))/lag(number_of_employees_middle)),
         pct.chg_top = formattable::percent((number_of_employees_top- lag(number_of_employees_top))/lag(number_of_employees_top)),
         pct.chg_bottom = (formattable::percent(number_of_employees_bottom - lag(number_of_employees_bottom))/lag(number_of_employees_bottom)),
         diff_middle = number_of_employees_middle - lag(number_of_employees_middle),
         diff_top = number_of_employees_top - lag(number_of_employees_top),
         diff_bottom =  number_of_employees_bottom - lag(number_of_employees_bottom))

####
city_gender <- r2 %>% group_by(data_year, gender2) %>% 
  summarise(number_of_employees_bottom = sum(number_of_employees_bottom),
            number_of_employees_middle = sum(number_of_employees_middle),
            number_of_employees_top= sum(number_of_employees_top)) %>% 
  group_by(gender2) %>%
  arrange(data_year, gender2) %>%
  mutate(pct.chg_middle = formattable::percent((number_of_employees_middle - lag(number_of_employees_middle))/lag(number_of_employees_middle)),
         pct.chg_top = formattable::percent((number_of_employees_top- lag(number_of_employees_top))/lag(number_of_employees_top)),
         pct.chg_bottom = (formattable::percent(number_of_employees_bottom - lag(number_of_employees_bottom))/lag(number_of_employees_bottom)),
         diff_middle = number_of_employees_middle - lag(number_of_employees_middle),
         diff_top = number_of_employees_top - lag(number_of_employees_top),
         diff_bottom =  number_of_employees_bottom - lag(number_of_employees_bottom))


####
agency_pop <- r2 %>% group_by(data_year, agency_name) %>% 
  summarise(number_of_employees_bottom = sum(number_of_employees_bottom),
            number_of_employees_middle = sum(number_of_employees_middle),
            number_of_employees_top= sum(number_of_employees_top)) %>% 
  group_by(agency_name) %>%
  arrange(data_year, agency_name) %>%
  mutate(pct.chg_middle = formattable::percent((number_of_employees_middle - lag(number_of_employees_middle))/lag(number_of_employees_middle)),
         pct.chg_top = formattable::percent((number_of_employees_top- lag(number_of_employees_top))/lag(number_of_employees_top)),
         pct.chg_bottom = (formattable::percent(number_of_employees_bottom - lag(number_of_employees_bottom))/lag(number_of_employees_bottom)),
         diff_middle = number_of_employees_middle - lag(number_of_employees_middle),
         diff_top = number_of_employees_top - lag(number_of_employees_top),
         diff_bottom =  number_of_employees_bottom - lag(number_of_employees_bottom))

####
agency_race <- r2 %>% group_by(data_year, agency_name, race_ethnicity) %>% 
  summarise(number_of_employees_bottom = sum(number_of_employees_bottom),
            number_of_employees_middle = sum(number_of_employees_middle),
            number_of_employees_top= sum(number_of_employees_top)) %>% 
  group_by(agency_name, race_ethnicity) %>%
  arrange(agency_name, data_year, race_ethnicity) %>%
  mutate(pct.chg_middle = formattable::percent((number_of_employees_middle - lag(number_of_employees_middle))/lag(number_of_employees_middle)),
         pct.chg_top = formattable::percent((number_of_employees_top- lag(number_of_employees_top))/lag(number_of_employees_top)),
         pct.chg_bottom = (formattable::percent(number_of_employees_bottom - lag(number_of_employees_bottom))/lag(number_of_employees_bottom)),
         diff_middle = number_of_employees_middle - lag(number_of_employees_middle),
         diff_top = number_of_employees_top - lag(number_of_employees_top),
         diff_bottom =  number_of_employees_bottom - lag(number_of_employees_bottom))

####
agency_gender <- r2 %>% group_by(data_year, agency_name, gender2) %>% 
  summarise(number_of_employees_bottom = sum(number_of_employees_bottom),
            number_of_employees_middle = sum(number_of_employees_middle),
            number_of_employees_top= sum(number_of_employees_top)) %>% 
  group_by(agency_name, gender2) %>%
  arrange(agency_name, data_year, gender2) %>%
  mutate(pct.chg_middle = formattable::percent((number_of_employees_middle - lag(number_of_employees_middle))/lag(number_of_employees_middle)),
         pct.chg_top = formattable::percent((number_of_employees_top- lag(number_of_employees_top))/lag(number_of_employees_top)),
         pct.chg_bottom = (formattable::percent(number_of_employees_bottom - lag(number_of_employees_bottom))/lag(number_of_employees_bottom)),
         diff_middle = number_of_employees_middle - lag(number_of_employees_middle),
         diff_top = number_of_employees_top - lag(number_of_employees_top),
         diff_bottom =  number_of_employees_bottom - lag(number_of_employees_bottom))
```

```{r}
# ----- IGNORE: ORIGINAL CODE -----
# focus on agencies who did poorly on our diversity metrics ------
# DSNY - gender (100)
# FDNY - gender (95)
# DOP - race (97)
# ACS - race (94)
# DHS - race (100)
# DOC - race (80)
# HRA - race (79)
# LPC - race (71)
# ----- IGNORE: ORIGINAL CODE -----

# new agencies
# DOITT - gender
# FDNY - gender
# NYPD - gender
# DSNY - gender
# DEP - gender
# DHS - race
# ACS - race
# DOP - race

poor_agency_race <- agency_race %>%  
  filter(agency_name %in% c('DHS', 'ACS', 'DOP'))
poor_agency_gender <- agency_gender %>%  
  filter(agency_name %in% c('DSNY', 'FDNY', 'NYPD', 'DOITT', 'DEP'))
```

```{r, fig.height = 4, fig.width=12}
# plot gender diversity ----

cp <- poor_agency_gender %>%
  select(data_year, pct.chg_middle, diff_middle) %>% 
  mutate(pct.chg_middle  = as.numeric(pct.chg_middle) * 100,
         pct.chg_middle = case_when(data_year==2018 ~ 0, TRUE ~ pct.chg_middle),
         diff_middle = case_when(data_year==2018 ~ 0, TRUE ~ diff_middle))

percent_plot <- cp %>%  filter(agency_name =='DSNY',gender2!="Other") %>% 
  ggplot(aes(x = data_year, y = pct.chg_middle)) +
  facet_wrap(~gender2, nrow=1) +
  geom_hline(yintercept=0, size = 0.5, color="grey") +
  geom_point(aes(color=data_year), show.legend = FALSE) +
  scale_color_discrete() + theme_nycc(facet=TRUE) +
  ggtitle("Percent Change") + xlab("Year") + ylab("Percent") +  easy_plot_title_size(14)

relative_plot <- cp %>%  filter(agency_name =='DSNY',gender2!="Other") %>% 
  ggplot(aes(x = data_year, y = diff_middle)) +
  facet_wrap(~gender2, nrow=1) +
  geom_hline(yintercept=0, size = 0.5, color="grey") +
  geom_point(aes(color=data_year)) +
  scale_color_discrete(name = "Year") + theme_nycc(facet=TRUE) +
  ggtitle("Relative Difference") + xlab("Year") + ylab("Number") +  easy_plot_title_size(14)

final <- grid.arrange(percent_plot, relative_plot, ncol=2,  top = textGrob("DSNY: Gender Diversity (2018-2020)",
                                                                           gp=gpar(fontsize=19, fontfamily="Georgia", font=2)))
ggsave(plot = final, "../figures/DSNY_diversity_by-gender.png")
```

```{r, fig.height = 4, fig.width=11.2}
# plot racial diversity ----

cp <- poor_agency_race %>%
  select(data_year, pct.chg_middle, diff_middle) %>% 
  mutate(pct.chg_middle  = as.numeric(pct.chg_middle) * 100,
         pct.chg_middle = case_when(data_year==2018 ~ 0, TRUE ~ pct.chg_middle),
         diff_middle = case_when(data_year==2018 ~ 0, TRUE ~ diff_middle))
cp$race_ethnicity <- recode(cp$race_ethnicity, 
                    "Ethnicity Unknown or Choose Not to Disclose" = "Ethnicity UCND") # to fit better in plot

percent_plot <- cp %>%  filter(agency_name =='DHS') %>% 
  ggplot(aes(x = data_year, y = pct.chg_middle)) +
  facet_wrap(~race_ethnicity, nrow=1) +
  geom_hline(yintercept=0, size = 0.25, color="grey") +
  geom_point(aes(color=data_year), show.legend = FALSE) +
  scale_color_discrete() + theme_nycc(facet=TRUE) +
  ggtitle("DOP Race") + xlab("Year") + ylab("Percent") +  easy_plot_title_size(14)

relative_plot <- cp %>%  filter(agency_name =='DHS') %>% 
  ggplot(aes(x = data_year, y = diff_middle)) +
  facet_wrap(~race_ethnicity, nrow=1) +
  geom_hline(yintercept=0, size = 0.25, color="grey") +
  geom_point(aes(color=data_year), show.legend = FALSE) +
  scale_color_discrete() + theme_nycc(facet=TRUE) +
  ggtitle("DOP Race") + xlab("Year") + ylab("Relative Difference") +  easy_plot_title_size(14)

final2 <- grid.arrange(percent_plot, relative_plot, nrow=2,  top = textGrob("DHS: Racial Diversity (2018-2020)",
                                                                           gp=gpar(fontsize=19, fontfamily="Georgia", font=2)))

ggsave(plot = final2, "../figures/DHS_diversity_by-race.png")
```
